name: Build Unity Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Unity
      uses: game-ci/unity-builder@v2.1.0
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_BUILDER_DOCKER_IMAGE: unityci/editor:ubuntu-2021.3.34f1-windows-mono
        
    - name: Build Windows
      run: |
        unity-builder \
          -projectPath . \
          -buildTarget StandaloneWindows64 \
          -customParameters "-quit -batchmode -nographics -silent-crashes -logFile"
      if: github.event_name == 'push'
        
    - uses: actions/upload-artifact@v4.6.0
      with:
        name: Windows Build
        path: build/StandaloneWindows64
      if: github.event_name == 'push'
        
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Unity
      uses: game-ci/unity-builder@v2.1.0
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        
    - name: Build Android
      run: |
        unity-builder \
          -projectPath . \
          -buildTarget Android \
          -customParameters "-quit -batchmode -nographics -silent-crashes -logFile"
      if: github.event_name == 'push'
        
    - uses: actions/upload-artifact@v4.6.0
      with:
        name: Android Build
        path: build/Android
      if: github.event_name == 'push'
        
  release:
    needs: [build-windows, build-android]
    runs-on: ubuntu-latest
    
    steps:
    - name: Download Windows Artifact
      uses: actions/download-artifact@v2
      with:
        name: Windows Build
        
    - name: Download Android Artifact
      uses: actions/download-artifact@v2
      with:
        name: Android Build
        
    - name: Create Release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.0
        release_name: Release v1.0.0
        
    - name: Upload Windows Asset
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./StandaloneWindows64/YourProjectName.exe
        asset_name: YourProjectName-Windows.exe
        asset_content_type: application/vnd.microsoft.portable-executable
        
    - name: Upload Android Asset 
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Android/YourProjectName.apk
        asset_name: YourProjectName-Android.apk
        asset_content_type: application/vnd.android.package-archive 